apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: liquibase
    spec:
      containers:
      - env:
        - name: SQL_SERVICE_HOST
          value: sql # The name of the SVC instance
        name: liquibase
        image: kapua/kapua-liquibase:latest
      restartPolicy: Never


