apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: liquibase
    spec:
      containers:
      - name: liquibase
        image: kapua/kapua-liquibase:latest
      restartPolicy: Never


